### ISSUE TITLE
Request failed for https://www.instagram.com returned code 400

### ISSUE THREAD

**Issue by Shin898** [chriskyfung/AutoFetcher-IG-Stories-to-GDrive#5]
I have this problem with the script... I follow all your advice for setting variables and start autorun but i don't know if i do something wrong or not. Thanks in advance for your help.

Request failed for https://www.instagram.com returned code 400. Truncated server response: {"message": "execution failure", "errors": [{"message": "execution error", "locations": []}], "status": "fail"} (use muteHttpExceptions option to examine full response) 
   at fetch_ig_stories(code:22:22)
    at test_fucntion(code:103:14)
    at test_bbcnews_ig(code:119:10)
    at test_pipeline(code:124:7)

**Comment by chriskyfung** [comment]
If the error code is 400, it is possibly due to the wrong URL passing from the function `getQuery()`.

Since you were running my test_pipeline, the `ig_user_id` used should be correct. Therefore, I think you defined an improper value to the `query_hash` variable. 

Instagram assigns different query_hash for various objects, such as user, story, stories, and so forth. I think you may grab the wrong one.

I've added how to find its value in the README file. Please refer to the updated instruction and try if it fixes your problem.

**Comment by Shin898** [comment]
Thanks for your updated instruction. Now seems all working good. I leave it open for next 24 hours and if I have some problems I'll write here.

P.S. Is possible add more than one target and save in different folder on google drive?

**Comment by harryfrancis4** [comment]
Hi! Yes this is possible by creating multiple functions and re-stating the gdrive_id variable like this.
Not sure if this is the cleanest way but it works.

function samrollinson() { 
  var e = {
      'parameter': {
        'usr': g_username,
        'pwd': g_password,
        'target' : { 'name': 'samrollinson', 'id':'197520684'}}};
gdrive_id = '1ZJOIgvcG6KNWEIic5ebG-abbfPngwu_D';
  doGet(e);}

**Comment by chriskyfung** [comment]
You can also create a function directly calling the myFunction without deploying as a web app.

**Example code**:

```js
function get_bbcnews {
   gdrive_id = '<ANOTHER_GDRIVE_FOLDER_ID>' ;
   myFunction( { "name": "bbcnews", "id":"16278726"} )
}
```
